### ISSUE TITLE
Sonar stats disappear and reappear on 10 second cycle

### ISSUE THREAD

**Issue by luthergr** [infragravity/sonar-docker#2]
Hello,
I am experimenting with Sonar to be our exporter for Prometheus stats. We have installed and configured it on several hosts running Windows 2008R2, 2012, and 2012R2, and we are successfully getting back stats on many of them, but not consistently.

I've discovered that there is a cyclical period where the stats appear on the web server (http://<hostname:port>/metrics) for approx. 10 seconds, then they disappear for approx. 10 seconds and so on. This is causing an issue with stats not being present when they are scraped by Prometheus. Our Linux hosts do not exhibit this behavior when presenting stats to Prometheus.

I've tried experimenting with the Runtime scrapeIntervalSeconds and ExporterCacheMilliseconds but they didn’t seem to have any effect on this issue.

Steps to reproduce:
1. Download Sonar zip from https://github.com/infragravity/sonar-docker/releases/download/v0.1.9/sonar-0190-win81-x64.zip
2. Create C:\Program Files\Sonar directory
3. Unzip install file to Sonar directory
4. Create files C:\Program Files\Sonar\out\Sonard.dll.config and C:\Program Files\Sonar\Sonar.config as below
5. Create service using sc.exe create sonard binpath= c:\sonar\out\Sonard.exe start= auto obj= LocalSystem depend= "WinRM"
6. In a browser, view http://<hostname:9190>/metrics. Repeatedly refresh the page, and note that the stats disappear and reappear on a cyclical basis. 

Sonard.dll.config
```
<?xml version="1.0"?>
<configuration>
<configSections>
<section name="Sonar" type="Infragravity.Sonar.SonarConfigurationSection, Sonar"/>
</configSections>
<appSettings>
<add key="ConfigPath" value="C:\Program Files\Sonar\Sonar.config"/>
<add key="RuntimeType" value="Service"/>
<add key="LogLevel" value="Warning"/>
<add key="LogPath" value="C:\Program Files\Sonar\Sonard.log"/>
<add key="ExporterPort" value="9190"/>
<add key="ExporterCacheMilliseconds" value="1000"/>
<add key="ExporterEnabled" value="true"/>
</appSettings>
</configuration>
```

Sonar.config

```
<?xml version="1.0"?>
<configuration>
  <configSections>
    <section name="Sonar" type="Infragravity.Sonar.SonarConfigurationSection, Sonar"/>
  </configSections>
  <connectionStrings>
    <add name="perfmon" providerName="mspdh" connectionString="." />
    <add name="sonar" providerName="wsman" connectionString="Server=sonar;" /> 
 </connectionStrings>
  <Sonar>
    <Runtime scrapeIntervalSeconds="5" skipSSLCheck="true" threads="1"/>
    <Schedules>   
    <add name="wmi_memory" query="win_wmi_memory_installed_kb" input="sonar" intervalSeconds="20" />
    <add name="memory" query="win_perfmon_memory_available" input="perfmon" intervalSeconds="20" />
    </Schedules>
    <Servers>
        <add name="sonar" url="http://localhost:5985/wsman" username="" password="" timeoutMilliseconds="1000" authType="Negotiate"/>   
    </Servers>
    <Queries>

    <add name="win_wmi_memory_installed_kb" filter="SELECT TotalVisibleMemorySize FROM Win32_OperatingSystem" resource="http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/*" namespace="root\cimv2"> <Tags> <add name="Name" value = "Name"/> </Tags> <Values> <add name="TotalVisibleMemorySize" value="CimType.UInt64"/> </Values> </add>

    <add name="win_perfmon_memory_available" type="raw" filter="" resource="." namespace="Memory"> <Tags> <add name="Name" value = "Name"/> </Tags> <Values> <add name="available_kbytes" value="Available KBytes"/> </Values> </add>
   
    </Queries>
  </Sonar>
 </configuration>
```

**Comment by dmitrios** [comment]
In Sonar.dll.config file, set larger interval to prevent metrics from expiring every second. For example:
`<add key="ExporterCacheMilliseconds" value="60000"/>` Note that Sonar metrics exposed to Prometheus are timestamped. This allows using larger intervals before Sonar will remove metrics that are no longer active: for example a process that exited.

**Comment by luthergr** [comment]
Thank you, this seems to have solved the issue.
When the cache is in place, does that mean metrics will not be updated until the cache expires? 
For instance, if I have a check that runs every 10s but my cache is 60s, will the check still be updated 6 times or will it only change once the cache expires?

**Comment by dmitrios** [comment]
Sonar updates given metric when it collects a new value regardless of cache. Cache interval is used to determine when to remove metric when it can no longer be collected. For example, a metric related to a  Windows process will be purged from cache after that process has been terminated.
