### ISSUE TITLE
Xml based config?? 

### ISSUE THREAD

**Issue by trondhindenes** [infragravity/sonar-docker#4]
This is awesome, but why on earth are config implemented as xml and not something more modern? Xml is infinitely more difficult to automate than json/yaml.

**Comment by dmitrios** [comment]
The system admins/engineers we talked to do not change configs very often and typically use automation to pick up one they need with Ansible or something else. If you have specific scenario in mind, please feel free to share.

**Comment by dmitrios** [comment]
You may find helpful this blog [post](http://leapfrogonline.io/articles/2018-05-11-exporting-windows-and-sql-server-metrics-to-prometheus-with-sonar/) from company who uses Sonar in production, especially if you use Ansible.
